Nomor 1 - Adrian Dwi Adinata

a) Buatlah sebuah array dengan perintah arrange yang nilai start dan
end adalah sebuah input!

In [1]:
# Import pustaka numpy terlebih dahulu

import numpy as np

In [4]:
# Buatlah sebuah array dengan perintah arrange yang nilai start dan end adalah sebuah input!

arr_1 = np.arange(1,28)
print(arr_1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


In [1]:
start = int(input('Mulai: '))
end = int(input('Selesai: '))

Mulai: 1
Selesai: 28


In [2]:
data_awal = np.arange(start, end)
data_awal

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

b) Dari array yang terbentuk tersebut, buatlah versi 2 dan 3
dimensinya!

In [5]:
#  Dari array yang terbentuk tersebut, buatlah versi 2 dan 3 dimensinya!

# Sebelum 2 dimensi kita lakukan 1 dimensi
arr_1 = np.arange(1,28)
print(arr_1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


In [6]:
# Untuk mengetahui jumlah dimensi pada data menggunakan fungsi ndim.
arr_.ndim

1

In [7]:
# Array arr_1 memiliki shape ...27, yaitu panjang array pada 1-dimensi array.
arr_1.shape

(27,)

In [11]:
# Mengubah arr_1 menjadi 2 dimensi dan menyimpan ke arr_2
arr_2 = arr_1.reshape(1, 27)

In [15]:
# Mencetak arr_2
arr_2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [12]:
# Untuk mengetahui jumlah dimensi pada data menggunakan fungsi ndim.
arr_2.ndim

2

In [16]:
# Array arr_2 memiliki shape 1, 27, yaitu panjang array pada 2-dimensi array.
arr_2.shape

(1, 27)

In [13]:
# Mengubah arr_1 menjadi 3 dimensi dan menyimpan ke arr_3
arr_3 = arr_1.reshape(3, 3, 3)

In [17]:
# Mencetak arr_3
arr_3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [14]:
# Untuk mengetahui jumlah dimensi pada data menggunakan fungsi ndim.
arr_3.ndim

3

In [18]:
# Array arr_3 memiliki shape 3, 3, 3, yaitu panjang array pada 3-dimensi array.
arr_3.shape

(3, 3, 3)