Nomor 2 - Adrian Dwi Adinata

a) Buatlah sebuah array 1 dimensi dari data random integer sebanyak 
“n”, dimana “n” tersebut adalah sebuah input !

In [1]:
# import pustaka numpy terlebih dahulu

import numpy as np

b) Batasan random juga ditentukan dalam input.


In [2]:
# input
arr = np.random.randint(1, 50, 16)

In [3]:
# Bangkitkan Array 1 Dimensi Dari Random Integer
arr

array([15,  3, 22, 18, 25,  4, 26,  2, 43,  9,  5, 32, 47, 33, 44,  8])

In [4]:
# input
n = int(input('Banyak data: '))
start = int(input('Mulai: '))
end = int(input('Selesai: '))

Banyak data: 16
Mulai: 1
Selesai: 50


In [5]:
data = np.random.randint(start, end, n)
data 

array([36, 16, 32, 32, 31, 24, 14, 38, 13, 26,  1,  3,  9,  1, 27, 31])

c) Ubahlah array 1 dimensi tersebut ke dalam bentuk 2 dimensi atau 
matrix!

In [6]:
# Dua Dimensi
arr_2 = arr.reshape(4, 4)

In [7]:
arr_2

array([[15,  3, 22, 18],
       [25,  4, 26,  2],
       [43,  9,  5, 32],
       [47, 33, 44,  8]])

In [8]:
arr_2.ndim

2

d) Setelah diubah ke bentuk 2 dimensi, setiap barisnya baliklah urutan 
datanya! Misalnya dari 1, 2, 3 menjadi 3, 2, 1.

In [9]:
# Tukar Posisi
arr_2[:, ::-1]

array([[18, 22,  3, 15],
       [ 2, 26,  4, 25],
       [32,  5,  9, 43],
       [ 8, 44, 33, 47]])

In [10]:
# Tukar Posisi
print(arr_2.transpose())

[[15 25 43 47]
 [ 3  4  9 33]
 [22 26  5 44]
 [18  2 32  8]]


In [11]:
# Tukar Posisi
arr_3 = arr_2[::-1]

In [12]:
arr_3

array([[47, 33, 44,  8],
       [43,  9,  5, 32],
       [25,  4, 26,  2],
       [15,  3, 22, 18]])